//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceRecord
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_accessories
    {
        public int id { get; set; }
        public Nullable<int> deviceId { get; set; }
        public string accessoryName { get; set; }
        public int serialNumber { get; set; }
        public System.DateTime guaranteeEnd { get; set; }
        public string seller { get; set; }
        public string type { get; set; }
        public System.DateTime entryDate { get; set; }
        public string price { get; set; }
        public string placement { get; set; }
        public string responsible { get; set; }
    
        public virtual devices devices { get; set; }
    }
}
