//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceRecord
{
    using System;
    using System.Collections.Generic;
    
    public partial class devices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public devices()
        {
            this.device_accessories = new HashSet<device_accessories>();
        }
    
        public int id { get; set; }
        public string deviceName { get; set; }
        public int serialNumber { get; set; }
        public System.DateTime guaranteeEnd { get; set; }
        public string seller { get; set; }
        public string type { get; set; }
        public System.DateTime entryDate { get; set; }
        public string price { get; set; }
        public string placement { get; set; }
        public string responsible { get; set; }
        public string ip { get; set; }
        public string networkName { get; set; }
        public string subnetMask { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<device_accessories> device_accessories { get; set; }
    }
}
